from .user import User
from .subject import Subject
from .course import Course
from .course_schedule import CourseSchedule
from .building import Building
from .room import Room
from .daily_menu import DailyMenu
from .menu_item import MenuItem
from .notice import Notice
from .notice_read import NoticeRead
from .notification_setting import NotificationSetting
from .shuttle import Shuttle
from .timetable import Timetable
from .timetable_course import TimetableCourse
from .custom_schedule import CustomSchedule
from .chat_room import ChatRoom
from .message import Message
from .graduation_standard import GraduationStandard
from .completed_course import CompletedCourse
from .wizard_selection import WizardSelection
from .friendship import Friendship
