"""add expo token and shuttle alert

Revision ID: 0c16a9230157
Revises: 87654a26cc5e
Create Date: 2026-05-29 00:28:08.740040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c16a9230157'
down_revision: Union[str, Sequence[str], None] = '87654a26cc5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_menu_date_uc', 'daily_menus', ['menu_date'])
    op.add_column('notification_settings', sa.Column('shuttle_alert', sa.Boolean(), nullable=True))
    op.add_column('notification_settings', sa.Column('expo_push_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_settings', 'expo_push_token')
    op.drop_column('notification_settings', 'shuttle_alert')
    op.drop_constraint('_menu_date_uc', 'daily_menus', type_='unique')
    # ### end Alembic commands ###
