"""add image_url to daily_menus

Revision ID: 1b5315c0262c
Revises: a7333cf237d9
Create Date: 2026-03-21 01:19:30.007717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5315c0262c'
down_revision: Union[str, Sequence[str], None] = 'a7333cf237d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_menus', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_menus', 'image_url')
    # ### end Alembic commands ###
