"""remove corner from daily_menus

Revision ID: 3d9e9c7047bb
Revises: 1b5315c0262c
Create Date: 2026-03-25 14:52:43.098220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9e9c7047bb'
down_revision: Union[str, Sequence[str], None] = '1b5315c0262c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_menus', 'corner')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_menus', sa.Column('corner', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
