"""add custom_schedules and share_token

Revision ID: 84a0eb0f8bfa
Revises: 3d9e9c7047bb
Create Date: 2026-03-26 09:26:32.478805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a0eb0f8bfa'
down_revision: Union[str, Sequence[str], None] = '3d9e9c7047bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetables', sa.Column('share_token', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'timetables', ['share_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timetables', type_='unique')
    op.drop_column('timetables', 'share_token')
    # ### end Alembic commands ###
